### ISSUE TITLE
Update contents with second event poster

### ISSUE THREAD

**Issue by RicardoSilveira23** [enlevo/posters#1]
Hey @LuchoTurtle 🐢, just a reminder that you've created a new poster for __enlevo__ but seems I can't find it here 💅.

Don't be 🦥. 

Aight, שלום

**Comment by LuchoTurtle** [comment]
Sure thing! I'll get it sorted next week when I have access to my computer 😎👍

**Comment by LuchoTurtle** [comment]
Added on https://github.com/enlevo/posters/commit/e8d25280f4cd0d443ca0240f0038749684878f5e 
:) 

Thanks for opening the issue! :D
